name: Github Actions Dotnet
on:
  push:
    paths-ignore:
      - "**/*.md"
jobs:
  Push-Job:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: 7.0.x
      DOTNET_CLI_TELEMETRY_OUTPUT: 3
      DOTNET_NOLOGO: true
      BUILD_CONFIGURATION: Release
      PROJECT_PATH: MyApp
      PROJECT_TEST_PATH: MyApp.Tests/MyApp.Tests.csproj
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up .NET Core version code ('${{ env.DOTNET_VERSION }}')
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true
      - name: Restore Packages
        run: dotnet restore ${{env.PROJECT_PATH}}
      - name: Build Package
        run: dotnet build --configuration ${{env.BUILD_CONFIGURATION}}
        working-directory: "${{env.PROJECT_PATH}}"
      - name: Run unit tests
        run: dotnet test ${{env.PROJECT_TEST_PATH}}
      - name: List commands used
        run: |
          ls /
          ls -la
      